Solution/PLY0012_Queensland.Bushfire/Controllers/LoginController.cs
using System.Web.Mvc;
using Umbraco.Web.Models;
using Umbraco.Web.Mvc;

namespace PLY0012_Queensland.Bushfire.Controllers
{
    public class LoginController : SurfaceController
    {
        public ActionResult Login(LoginModel model)
        {
            if (!ModelState.IsValid)
                return CurrentUmbracoPage();

            if (Members.Login(model.Username, model.Password)) {
                return Redirect(model.RedirectUrl);
            }

            ModelState.AddModelError("", "Invalid login");

            return CurrentUmbracoPage();
        }

        public ActionResult Logout()
        {
            Members.Logout();
            return Redirect("/");
        }
    }
}

Solution/PLY0012_Queensland.Bushfire/Controllers/RegisterController.cs
using System.Web.Mvc;
using PLY0012_Queensland.Bushfire.Models;
using Umbraco.Web.Mvc;

namespace PLY0012_Queensland.Bushfire.Controllers
{
    public class RegisterController : SurfaceController
    {
        public ActionResult Register(RegisterModel model)
        {
            if (!ModelState.IsValid)
                return CurrentUmbracoPage();

            var memberService = Services.MemberService;
            if (memberService.GetByEmail(model.Email) != null) {
                ModelState.AddModelError("", "A member with that email already exists");
                return CurrentUmbracoPage();
            }

            var member = memberService.CreateMemberWithIdentity(model.Email, model.Email, model.Name, "IntranetUser");
            member.SetValue("biography", model.Biography);
            member.SetValue("avatar", model.Avatar);

            memberService.Save(member);
            memberService.AssignRole(member.Id, "Intranet Users");

            memberService.SavePassword(member, model.Password);

            // log user in
            Members.Login(model.Email, model.Password);

            return Redirect("/");
        }
    }
}

Solution/PLY0012_Queensland.Bushfire/Controllers/SearchController.cs
using Examine;
using Examine.SearchCriteria;
using System.Linq;
using System.Web.Mvc;
using PLY0012_Queensland.Bushfire.Models;
using Umbraco.Web.Mvc;

namespace PLY0012_Queensland.Bushfire.Controllers
{
    public class SearchController : SurfaceController
    {
        [ChildActionOnly]
        public ActionResult Search(string query)
        {
            var model = new SearchModel { Query = query };
            if (!string.IsNullOrEmpty(query)) {
                // search criteria #1
                //var criteria = ExamineManager.Instance.CreateSearchCriteria(BooleanOperation.Or)
                //    .NodeTypeAlias("statusUpdate").And().Field("bodyText", query).Compile();

                // boost
                //var criteria = ExamineManager.Instance.CreateSearchCriteria(BooleanOperation.Or)
                //    .RawQuery("nodeName: " + query + "^2 bodyText:" + query);

                // fuzzy
                var criteria = ExamineManager.Instance.CreateSearchCriteria(BooleanOperation.Or)
                    .RawQuery("nodeName: " + query + "~0.7 bodyText:" + query);

                model.SearchResults = Umbraco.TypedSearch(criteria);
            }
            return PartialView("~/Views/Partials/SearchPartial.cshtml", model);
        }
    }
}

Solution/PLY0012_Queensland.Bushfire/Controllers/StatusUpdateController.cs
using System.Web.Mvc;
using PLY0012_Queensland.Bushfire.Models;
using Umbraco.Web.Mvc;
using PLY0012_Queensland.Bushfire.Level2;
using System.Collections.Generic;

namespace PLY0012_Queensland.Bushfire.Controllers
{
    public class StatusUpdateController : SurfaceController
    {
        public PartialViewResult Render() {
            return PartialView("StatusUpdatePartial", new StatusUpdateModel());
        }        
        public ActionResult Create(StatusUpdateModel model)
        {
            //var fakeValue = "This is a test";
            //fakeValue = fakeValue.Substring(999);

            //if (!ModelState.IsValid)
            //    return CurrentUmbracoPage();

            if (!ModelState.IsValid)
                return CurrentUmbracoPage();

            var currentPageId = UmbracoContext.PageId.Value;
            var contentService = Services.ContentService;
            var statusUpdateTitle = Umbraco.Truncate(Umbraco.StripHtml(model.BodyText), 50).ToString();
            var content = contentService.CreateContent(statusUpdateTitle, currentPageId, "statusUpdate");
            content.SetValue("bodyText", model.BodyText);

            var ms = Services.MediaService;
            if (model.Files.HasFiles() && model.Files.ContainsImages())
            {
                var folder = ms.CreateMedia(statusUpdateTitle, -1, "Folder");
                ms.Save(folder);
                content.SetValue("mediaFolder", folder.Id);

                List<string> relatedMedia = new List<string>();

                foreach (var file in model.Files) {
                    if (file.IsImage()) {
                        var image = ms.CreateMedia(file.FileName, folder, "Image");
                        image.SetValue("umbracoFile", file);
                        ms.Save(image);
                        relatedMedia.Add(image.Id.ToString());
                    }
                }

                content.SetValue("relatedMedia", string.Join(",", relatedMedia.ToArray()));
            }

            // member
            if (Members.IsLoggedIn()) {
                var memberId = Members.GetCurrentMemberId();
                content.SetValue("memberId", memberId);
            }

            contentService.PublishWithStatus(content);

            return RedirectToCurrentUmbracoPage();
        }
    }
}

Solution/PLY0012_Queensland.Bushfire/Views/HomePage.cshtml
@inherits UmbracoTemplatePage
@using System; 
@using System.Collections.Generic; 
@using System.Linq; 
@using System.Text.RegularExpressions; 
@using System.Security.Cryptography; 
@using System.Text;
@{
    Layout = "Layout.cshtml";

    String password = "pass123";
    HMACSHA1 hash = new HMACSHA1();
    hash.Key = Encoding.Unicode.GetBytes(password);
    string encodedPassword = Convert.ToBase64String(hash.ComputeHash(Encoding.Unicode.GetBytes(password))); 
}
<div class="jumbotron">
    <h1>@(Model.Content.GetPropertyValue<string>("SiteName", true))</h1>
    
    @Html.Raw(Model.Content.GetPropertyValue<string>("BodyText"))

    <p>
        <a class="btn btn-lg btn-primary" href="/Stream" role="button">Post a Status Update</a>
    </p>
</div>
<div>
    <!-- This would be a great place to put the ListStatus Updates Macro -->
</div>

Solution/PLY0012_Queensland.Bushfire/Views/Layout.cshtml
@using ClientDependency.Core.Mvc
@inherits UmbracoTemplatePage
@{
    Layout = null;
    
    Html.RequiresJs("~/scripts/jquery-1.11.0.min.js");
    Html.RequiresJs("~/scripts/bootstrap.min.js");
    Html.RequiresJs("~/scripts/level2.js");
        
    Html.RequiresCss("~/css/bootstrap.min.css");
    Html.RequiresCss("~/css/bootstrap-theme.min.css");
    Html.RequiresCss("~/css/level2.css");
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@Model.Content.Name</title>

    @Html.RenderCssHere()

    <!--[if lt IE 9]>
      <script src="/scripts/html5shiv.min.js"></script>
      <script src="/scripts/respond.min.js"></script>
    <![endif]-->

</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">@(Model.Content.GetPropertyValue<string>("SiteName", true))</a>
            </div>
            <div class="navbar-collapse collapse">
                
                @Html.CachedPartial("TopNavigationPartial", Model, 5, true) 
            
                <div class="col-xs-12 col-sm-4 col-md-4 navbar-right">
                    <form class="navbar-form" role="search" method="POST" action="/search">
                        <div class="input-group">
                            <label for="search-box" class="sr-only">Search Term:</label>
                            <input id="search-box" type="text" name="query" class="form-control" placeholder="Search" />
                            <div class="input-group-btn">
                                <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                            </div>
                        </div>
                    </form>
                </div>
                @{
                    Html.RenderPartial("~/Views/Partials/LoginStatusPartial.cshtml", Model);
                }
            </div>
        </div>
    </div>
    <div class="container">
        <div class="col-md-8 col-xs-12">
            @RenderBody()
        </div>
        <div class="col-md-4 col-xs-12">
            @Html.CachedPartial("WatercoolerGalleryPartial",Model,0,true)
        </div>
    </div>
      
    @Html.RenderJsHere()
    <script src="~/scripts/jquery.validate.min.js"></script>
    <script src="~/scripts/jquery.validate.unobtrusive.js"></script>

</body>
</html>

Solution/PLY0012_Queensland.Bushfire/Views/Login.cshtml
@using Umbraco.Web.Models
@inherits UmbracoTemplatePage
@{
    Layout = "Layout.cshtml";
}
<div class="bodyText">
    @Html.Raw((Model.Content.GetPropertyValue<string>("BodyText")))
</div>

<!-- Render login partial here -->
@Html.Partial("LoginPartial", new LoginModel());

Solution/PLY0012_Queensland.Bushfire/Views/Register.cshtml
@using PLY0012_Queensland.Bushfire.Models
@inherits UmbracoTemplatePage
@{
    Layout = "Layout.cshtml";
}
<div class="bodyText">
    @Html.Raw((Model.Content.GetPropertyValue<string>("BodyText")))
    @Html.Partial("RegisterPartial", new RegisterModel())
</div>

<!-- Render Registration form here -->

Solution/PLY0012_Queensland.Bushfire/Views/Search.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Layout.cshtml";
}
<div class="bodyText">
    @Html.Raw((Model.Content.GetPropertyValue<string>("BodyText")))
</div>
<div>
	<!-- Call Search child action here -->
    @Html.Action("Search", "Search")
</div>

Solution/PLY0012_Queensland.Bushfire/Views/Stream.cshtml
@using PLY0012_Queensland.Bushfire.Models
@inherits UmbracoTemplatePage
@{
    Layout = "Layout.cshtml";
}
<div class="jumbotron" id="statusForm">
    <div>Using RenderPartial:</div>
    @{ Html.RenderPartial("StatusUpdatePartial", new StatusUpdateModel()); }

    <div>Using Partial:</div>
    @Html.Partial("StatusUpdatePartial", new StatusUpdateModel());

    <div>Using Action (PartialViewResult):</div>
    @Html.Action("Render", "StatusUpdate");
</div>

<div>
    <!-- This would be a great place to put the ListStatus Updates Macro -->
	@Umbraco.RenderMacro("ListStatusUpdates", new {numberOfItems="[@numberOfItems]"})
</div>

Solution/PLY0012_Queensland.Bushfire/Views/TextPage.cshtml
@inherits UmbracoTemplatePage
@{
    Layout = "Layout.cshtml";
}
<div class="bodyText">
    @Html.Raw((Model.Content.GetPropertyValue<string>("BodyText")))
</div>